FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY . .
RUN dotnet publish JustJoinITBackend.Worker/JustJoinITBackend.Worker.csproj \
    -c Release -o /app/publish \
    -p:SolutionDir=/data/

FROM mcr.microsoft.com/dotnet/runtime:10.0
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "JustJoinITBackend.Worker.dll"]
